version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development